dictionary = [
    {"english" :"some",
    "chinese" : "些",
    "enYin" : "xie",
    "pinyin" : "xiē",
},
{"english" : "a",
    "chinese" : "个",
    "enYin" : "ge",
    "pinyin" : "ge",
},
{"english" : "piece", 
    "chinese" : "块",
    "enYin" : "kuai",
    "pinyin" : "kuài",
},
{"english" : "volume",
    "chinese" : "本",
    "enYin" : "ben",
    "pinyin" : "běn",
},
{"english" : "year",
    "chinese" : "岁",
    "enYin" : "sui",
    "pinyin" : "suì",
},
{"english" : "tea",
    "chinese" : "茶",
    "enYin" : "cha",
    "pinyin" : "chá",
},
{"english" : "fruit",
    "chinese" : "水果",
    "enYin" : "shuiguo",
    "pinyin" : "水果",
},
{"english" : "apple",
    "chinese" : "苹果",
    "enYin" : "pingguo",
    "pinyin" : "píngguǒ",
},
{"english" : "water",
    "chinese" : "水",
    "enYin" : "shui",
    "pinyin" : "shuǐ",
},
{"english" : "vegetable",
    "chinese" : "菜",
    "enYin" : "cai",
    "pinyin" : "cài",
},
{"english" : "rice",
    "chinese" : "米饭",
    "enYin" : "mifan",
    "pinyin" : "mǐfàn",
},
{"english" : "cup",
    "chinese" : "杯子",
    "enYin" : "beizi",
    "pinyin" : "bēizi",
},
{"english" : "home",
    "chinese" : "家",
    "enYin" : "jia",
    "pinyin" : "jiā",
},
{"english" : "restaurant",
    "chinese" : "饭店",
    "enYin" : "fandian",
    "pinyin" : "fàndiàn",
},
{"english" : "school",
    "chinese" : "学校",
    "enYin" : "xuexiao",
    "pinyin" : "xuéxiào",
},
{"english" : "store",
    "chinese" : "商店",
    "enYin" : "shangdian",
    "pinyin" : "shāngdiàn",
},
{"english" : "apple",
    "chinese" : "医院",
    "enYin" : "pingguo",
    "pinyin" : "píngguǒ",
},
{"english" : "hospital",
    "chinese" : "苹果",
    "enYin" : "yiyuan",
    "pinyin" : "yīyuàn",
},
{"english" : "train station",
    "chinese" : "火车站",
    "enYin" : "huochezhan",
    "pinyin" : "huǒchēzhàn",
},
{"english" : "morning",
    "chinese" : "上午",
    "enYin" : "shangwu",
    "pinyin" : "shàngwǔ",
},
{"english" : "noon",
    "chinese" : "中午",
    "enYin" : "zhongwu",
    "pinyin" : "zhōngwǔ",
},
{"english" : "afternoon",
    "chinese" : "下午",
    "enYin" : "xiawu",
    "pinyin" : "xiàwǔ",
},
]

